### ISSUE TITLE
Stuck on prompt

### ISSUE THREAD

**Issue by lucasdmoyer** [ivannieto/archer-t2u-ubuntu-installer#10]
I keep getting the,
Please, disconnect all devices you're trying to install and press [I]

I have unplugged the wifi adapter and only have speakers, keyboard, and mouse plugged in.
I have python3 installed and am using the Archer T2U from TP-Link.

**Comment by Riflio** [comment]
Type lowercase "i"

**Comment by ivannieto** [comment]
@lucasdmoyer first unplug the wifi adapter and then install. It's intended to guide the user to install properly.
