### ISSUE TITLE
Network Manager and Terminal Crashing

### ISSUE THREAD

**Issue by ph03n1x112** [ivannieto/archer-t2u-ubuntu-installer#12]
Hi  Ivan,

First i wish to thank you for the excellent job you have done here, i have and old computer which i'd tryed every single solution find in english and portuguese and no one worked. With your driver it's work in first try. 

I´m with a little trouble here and i want to ask if you can help me. This old computer that i have is an Intel Core 2Duo in a 945GCT-M, 2GiB RAM with the T2U. The drive work very well but in my new computer AMD Ryzen 1500x,  Asus B350M-A, 8GiB i have the following issue. The drive install very well, but after restart the computer and run the "t2u-driver" the network stop respond, i can do anything in the system, except restart the network manager manually because it's don't respond to the commands neither the terminal, if i type something there i don't receive anything back, neither a error message.

If you can give me a help, just contact me. I want a lot resolve this.

Once again, congratulations and thank for what you done here. Is an excellent job.

Thank you

**Comment by ivannieto** [comment]
Thanks for your kind words. Glad to help you.

Based on your description. If you type ifconfig you should see your adapter names, it's probably related with that. t2u-driver file is based to work on ra0, so check that.

Let me know.

**Comment by ivannieto** [comment]
@ph03n1x112 please see how #14 solved this problem.

**Comment by ph03n1x112** [comment]
The error that appears to him, was what appears to me before trying your driver.

Now, this is not the problem. I can see the interface, i can enable the dongle but after restart the network-manager it does't work. What stop to work is the network-manager. If you want i can record a little video to show whats happen. 

For while i decide that soon i'll make a network cable instead get angry with this damn device.

**Comment by ivannieto** [comment]
Yes it is somewhat hard to manage, it's totally preferable nw cable for that.

It was one of my worst buys, but also learned a lot with it.

Send over a screen record and lets see whats happening. Try to record in gif format and hide all the sensible stuff for you.

**Comment by ivannieto** [comment]
Had you tried to sudo service network-manager restart?

**Comment by dmazin** [comment]
Yep, seeing the same thing. Clean install of 16.04.
`sudo ifconfig ra0 up` succeeds but `sudo service network-manager restart` causes `sudo` to hang even in new terminal sessions. What logs should I follow?

**Comment by ivannieto** [comment]
@dmazin try to:

```bash
sudo ifconfig ra0 down && \
sudo service networking restart && \
sudo service network-manager restart
```

@ph03n1x112 drop a mail. ivan.nieto.sousa@gmail.com

**Comment by ph03n1x112** [comment]
@ivannieto i've sended you an e-mail, have you already checked it? 

Thanks for your time :D

**Comment by ivannieto** [comment]
Sorry for the late @ph03n1x112.  Sadly I will discontinue the manteinance on this repository. I can't test the dongle anymore (got rid of it) and got no time to work on this.

I had a look at the videos. Maybe the network-manager or networking are not restarting. Do it by hand with the proper commands to restart the services.

Again sorry I can't help anymore.


Good luck! ☺
