### ISSUE TITLE
Uninstall not working

### ISSUE THREAD

**Issue by axelvaindal** [ivannieto/archer-t2u-ubuntu-installer#13]
Hi, 

I have installed your driver for the archer t2u wifi key but I cannot uninstall it with your script.
Based on the source, there must be something weird on the code that makes it failing.
I uninstalled your script running the command in the uninstaller by hand.
It seems to have done the trick for now.

**Comment by ivannieto** [comment]
Thanks for the call. Sadly I will discontinue the manteinance on this repository. I can't test the dongle anymore (got rid of it) and got no time to work on this.

Feel free to fork and adapt the code as you wish! ❤
