### ISSUE TITLE
Error while trying to enable the driver

### ISSUE THREAD

**Issue by dazjavier** [ivannieto/archer-t2u-ubuntu-installer#14]
Hi,
First of all thanks for the amazing work.
I'm getting this error while trying enable the driver:

`ra0: ERROR while getting interface flags: No such device`

I tried to reinstall, but nothing.

Would appreciate any help.

Kernel Version: 4.13.0-37-generic
Ubuntu Version: Ubuntu 17.10

Thanks.

**Comment by ivannieto** [comment]
Hi Javier,

Please read my response from #12 . I think is related to that, please report your interface names and let's see what's happening.

**Comment by dazjavier** [comment]
Thanks for replying @ivannieto.
It was because I have Secure Boot enabled. Disabling that, everything start working.
