### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by JLM89** [ivannieto/archer-t2u-ubuntu-installer#15]
First of all, thank you and congrats for your work.

I am very new to this, sorry if i am trying to do this in the wrong way. I have ubuntu 17.10 and python 3.6 (withou subscrive the previous 2.x version) then i try the first command in the read.me file to start (git clone --branch 2.0.0 git@github.com:ivannieto/archer-t2u-ubuntu-installer.git) and got this:

$ git clone --branch 2.0.0 git@github.com:ivannieto/archer-t2u-ubuntu-installer.git
Cloning into 'archer-t2u-ubuntu-installer'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights

**Comment by JLM89** [comment]
It was a really newbie question, I configurate a SSH key in github and the instalation works just fine. 
Thank you very much, you can close or delete that.

**Comment by ivannieto** [comment]
Thanks for the update @JLM89. Closing.

:heart:
