### ISSUE TITLE
Does not start on boot

### ISSUE THREAD

**Issue by mmccool** [ivannieto/archer-t2u-ubuntu-installer#17]
This may be "expected behaviour", but if so, consider this a feature request, not a bug report ;).

I'm using this for a headless system and I need it to come up on boot as I need to log into the computer over the network.  Currently you have to run "t2u-driver" every time, AND interactively give it an "e".
I suspect I should also be disabling it before shutting down, but that is a nuisance, too.

Anyway, without the driver working "automatically" I can't use it for what I'm doing.   At the very least the command to enable/disable should be modified to take an argument (or just be two separate scripts) to make it easier to put in startup/shutdown scripts.

**Comment by ivannieto** [comment]
First, thanks a lot for the request, it's a great addition, but sadly I will discontinue the maintenance on this project, just because I can't test the dongle anymore and got rid of it.

Feel free to fork it and adapt it as you wish! It's an easy script to follow. ☺
