### ISSUE TITLE
Uptade to 18.04 Bionic Beaver

### ISSUE THREAD

**Issue by JLM89** [ivannieto/archer-t2u-ubuntu-installer#18]
First, thank you again for the great job, I was using the archert2u and it was working just fine in the 17.10 version.

It was working so fine that i end up forgeting about and updating the distro for the 18.04 bionic beaver, now the driver doesn´t work of course. Do you pretend uptdate the instalation process to work on 18.04?

Thank you and congrats.

**Comment by ivannieto** [comment]
Thanks a lot for the kind words. The work for 17.10 came from a contributor! ☺

Sadly I will discontinue the manteinance on this repository. I can't test the dongle anymore (got rid of it) and got no time to work on this.

Give it a try to update the code to 18.04 ☺, it should not be hard.

Cheers!

**Comment by cnaveiro** [comment]
Hi @ivannieto If you can make the next update for us, can you tell us how to do that please?
Thanks in advance!
