### ISSUE TITLE
GUI Questions

### ISSUE THREAD

**Issue by ivannieto** [ivannieto/archer-t2u-ubuntu-installer#3]
* Qt5?
* Tkinter?

Check pros and cons about each on using them for a simple windowed app.

**Comment by wheelerlaw** [comment]
GUI for what? It's a driver. Unless you're talking about adding a GUI for installation. But even in that case, a GUI is still wrong, it would be more appropriate to package it as a .deb or .rpm, etc.

**Comment by ivannieto** [comment]
Agree with you totally. Closing it. Too old to be held here.
