### ISSUE TITLE
Default configuration works better for 16.04

### ISSUE THREAD

**Issue by ivannieto** [ivannieto/archer-t2u-ubuntu-installer#4]
Research why.

**Comment by emazjr** [comment]
Hi!
The drive is already installed, however the network-manager hang; doesn't work after drive enabled.
Ubuntu 16.04 LTS
Dell Inspiration
Emerson

**Comment by ivannieto** [comment]
I'm gonna reupload properly this repo this next week, so you can download the correct version, thank you for throwing this issue. Please open a new one so I can track it.

Also, you can still try the previous version from the commit a9e5d2203cf91ac5c0164dbf3def550dfdc9bec2

**Comment by emazjr** [comment]
Tanks  a lot, Ivanieto!

I do appreciate that.

Best Regards

Emerson
