### ISSUE TITLE
Can't install on ubuntu 17.10

### ISSUE THREAD

**Issue by kaszperro** [ivannieto/archer-t2u-ubuntu-installer#6]
Hi, could you make it possible to install driver on ubuntu 17.10? Kernel version is: 4.13.
Once I try to install I get following error:
In function ‘memcpy’,
    inlined from ‘rt_ioctl_iwaplist’ at /home/kasper/Pulpit/archer-t2u-ubuntu-installer/driver-files/os/linux/../../os/linux/sta_ioctl.c:696:2:
./include/linux/string.h:305:4: error: call to ‘__read_overflow2’ declared with attribute error: detected read beyond size of object passed as 2nd parameter
    __read_overflow2();
    ^~~~~~~~~~~~~~~~~~

Thanks!

**EDIT**
I've fixed it, take a look at pull requests

**Comment by ivannieto** [comment]
Thanks a lot @kaszperro :D
