### ISSUE TITLE
Linux mint 18.3 issue

### ISSUE THREAD

**Issue by lucky0511** [ivannieto/archer-t2u-ubuntu-installer#8]
Hi Ivan.

i have the stick T2U and i want to use it for my laptop to get faster connect 5Ghz
its not work with linux mint 18.3
edit: i installed Ubuntu 17.10 and its still not working.
its available in lsusb and when i enable wifi by "sudo t2u-driver", i saw 2 icon wifi (1 of my laptop, 1 of T2U) but both of them show no signal, no connection. when i click on on/off my laptop freezing for few second, or hang forever.
i dont know why,, hope you got some time to help me fix it out. if you need any infomation just ask.
thank you in advance

**Comment by ivannieto** [comment]
This repository is intended to work on Ubuntu LTS versions (17.10 is not LTS), and Mint is not supported as well. If anyone comes with the proper fix it'll be merged, I can't maintain this repo updated nowadays. Sorry.
