### ISSUE TITLE
mint 17.3 64 bit after restart no device

### ISSUE THREAD

**Issue by ascidro** [ivannieto/archer-t2u-ubuntu-installer#9]
after install everything works, after shutdown next start it doesnt.
Coming from Amiga i dont know much about Linux.
Is there a startup sequence where i have to assign it?

**Comment by ivannieto** [comment]
Once you had restarted, you can enable or disable the driver. Plug your USB dongle and run:

$ sudo t2u-driver

**Comment by ascidro** [comment]
i did ...i think it is someting like that?
/etc/network/ seems to be the mint  /etc/sysconfig/network-scripts/

i did
sudo gedit ifconfig-ra0
/etc/network $ sudo gedit ifcfg-ra0




AutoLoad at BootTime

    Choose ra0 as first RT2870 WLAN card, ra1 for the second RT2870 WLAN card, etc.

    Create/Edit ifconfig-ra0 file in /etc/sysconfig/network-scripts/, search for the line alias ra0 xxxx and add/edit:

    alias ra0 rt2870sta

    Create/Edit these lines in the file /etc/sysconfig/network-scripts/ifcfg-ra0:
        DEVICE='ra0'
        ONBOOT='yes'
        For DHCP use add: BOOTPROTO='dhcp'

    To ease the Default Gateway setting, add in /etc/sysconfig/network:
        GATEWAY=x.x.x.x


AutoLoad at BootTime

    Choose ra0 as first RT2870 WLAN card, ra1 for the second RT2870 WLAN card, etc.

    Create/Edit ifconfig-ra0 file in /etc/sysconfig/network-scripts/, search for the line alias ra0 xxxx and add/edit:

    alias ra0 rt2870sta

    Create/Edit these lines in the file /etc/sysconfig/network-scripts/ifcfg-ra0:
        DEVICE='ra0'
        ONBOOT='yes'
        For DHCP use add: BOOTPROTO='dhcp'

    To ease the Default Gateway setting, add in /etc/sysconfig/network:
        GATEWAY=x.x.x.x

**Comment by ivannieto** [comment]
But anyways, this repo is not intended to work with other system than Ubuntu versions, not Mint. No support will be provided.

**Comment by ascidro** [comment]
well it worked with a reinstall anyway..thx

**Comment by ivannieto** [comment]
Sorry @ascidro I can't find the time to maintain this repo nowadays. :)
